version: '3.8'
services:
  vittostore:
    build: .
    container_name: vittostore-app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./public:/usr/src/app/public
      - ./config:/usr/src/app/config
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
    # Si usas una base de datos externa, agrega aquí el servicio
    # depends_on:
    #   - mongo
    # networks:
    #   - vittostore-net
#networks:
#  vittostore-net:
#    driver: bridge
